### ISSUE TITLE
(setf r (conc r a b)) is a slow pattern! Use with-output-to-string and write instead!

### ISSUE THREAD

**Issue by ejbs** [ritschmaster/caveman2-widgets#1]
Hi!

I saw that you use CONCATENATE a lot, that is a pretty slow operation. Using with-output-to-string is faster and as easy to read!

I did the following perf. "tests" (really simple, I admit) and found the following:

```
CL-USER> (time
      (progn
        (let ((r ""))
          (loop for i from 0 to 10000 do
           (setf r (concatenate 'string r "a a a"
                      "bbb")) ))
        1))
Evaluation took:
  0.749 seconds of real time
  0.757354 seconds of total run time (0.727528 user, 0.029826 system)
  [ Run times consist of 0.260 seconds GC time, and 0.498 seconds non-GC time. ]
  101.07% CPU
  2,091,091,587 processor cycles
  1,600,628,864 bytes consed

1
CL-USER> (time
      (progn
        (with-output-to-string (r)
          (loop for i from 0 to 100000 do
           (format r "a a a")
           (format r "bbb") ))
        1))
Evaluation took:
  0.013 seconds of real time
  0.012616 seconds of total run time (0.012616 user, 0.000000 system)
  100.00% CPU
  34,586,506 processor cycles
  7,343,088 bytes consed

1
```

Note that w-o-t-s is 100k rounds and conc is only 10k (conc wouldn't terminate after I waited for about 10 seconds).

As an example of a re-write I did this for render-widget of <composite-widget>

Before

```
(defmethod render-widget ((this <composite-widget>))
  (let ((ret-val ""))
    (dolist (widget (slot-value this 'widgets))
      (setf ret-val
            (concatenate 'string
                         ret-val
                         (render-widget widget))))
    ret-val))
```

After

```
(defmethod render-widget ((this <composite-widget>))
  (with-output-to-string (ret-val)
    (dolist (widget (slot-value this 'widgets))
      (format ret-val (render-widget widget)))))
```

I haven't ported the rest of the code since I wanted to pass it by you first and I'm happy to help if you think it's a good idea. I understand that perf. isn't necessarily your goal but why be slow when you can be fast with exactly the same amount of effort? Also it probably matters if someone would like to deploy this and serve it to a reasonable number of people.

**Comment by ritschmaster** [comment]
Hello!

First of all I want to thank you that you are interested in my library! Secondly your idea sounds great to me! I used CONCATENATE at first because I needed something that worked and I didn't know WITH-OUTPUT-TO-STRING. Although the RAM overhead for the stream is really large (as you mentioned) I think it is the way to go. Especially because that macro is way more intuitive then setting a return value all the time. Further I guess if you compile it with ECL or CCL you will get better RAM usage.

So I would be happy if you want to contribute to this project with that work! If you need a sample caveman2-project - to save time - send me a mail (from their I took the examples in the Readme).
