### ISSUE TITLE
Using JavaScript within a widget

### ISSUE THREAD

**Issue by ghost** [ritschmaster/caveman2-widgets#3]
Hello,

I'm also developing some extra modules for caveman2. For some time I was thinking about wrapping everything into widgets and now I found this project. Boy am I relieved to find that so much work is already done. Currently I'm been making an authentication/authorization modules and was thinking of getting started with other e-commerce related modules such as catalog and cart.

Everything is pretty early at this point and nothing is public yet, but I do like the idea of wrapping all that I created into these widgets rather than developing the widget library on my own. What my question is, is to know how would I go about using JavaScript within these widgets. I can see that asynchronous refreshing is handled by javascript, but how could the javascript be placed within the widget itself?
- WouldI write the javascript as a separate file that is then to be served by the server and the functions referenced in the widget?
- Would I write the javascript as parenscript somewhere in a separate file and compile that to javascript having the rest go as above?
- Would I write the javascript inside the widget and as either raw javascript or as parenscript or other language that compiles to javascript and let the widget library handle the rest?

Currently I would probably go with the raw javascript route, but I would like to know what is planned or is this feature something someone else would have to develop?

**Comment by ritschmaster** [comment]
Hello and thank you very much for your interest!

Before I answer your question consider that widgets refresh either after a period of time or after some a button-widget/link-widget has been clicked. So the most common thing - a stateful widget which only uses HTML - is supported right now.

To come to your question: on my Website I am using Weblocks currently and it was possible for me to deliver JavaScript-Code (enclosed in a script tag) via the RENDER method. This means that the JavaScript-Code gets called from within the body tag (which is sufficient for me). Therefore that's the encouraged way to do it right now.

If this is not sufficient for your application your first two solutions would work right now. The third is not supported at the moment and I haven't actually considered that beside from what I have described above. But I think you have meant that anyway. 

So to your last question: no, it is not planned but if there you or anyone describe a better way to do it, I would even implement it myself - maybe something with Require.js (if that's still a thing)?

**Comment by ghost** [comment]
Thank you for the quick response.

I will probably use the way you are doing it right now for the time being until I start needing something more.

I was looking through the code and think I got some grasp on how this script-widget might be implemented. This idea is by no means complete but could serve as a starting point for the discussion.  

Starting to think with compatibility in mind, the widget should probably fall back to informing the user about requiring javascript to work. Probably easy to implement with the `<noscript>` tag

Also it should probably be easily embedable to other sites but only if explicitly allowed by the site owner. Important for security with systems requiring logins and other sensitive data to prevent malicious sites from abusing the system. Probably the app would have to provide an API to request the widget and not allow direct access to js-files and even then probably surround the widget with a notification that it is imported.

On the code side the widget should probably be able to host anything from simple product carousels to complete checkout processes such as the Klarna checkout for reference and even complete webgl applications. The widget shouldn't care what is inside. Therefore, it should be possible to write the simple code within the widget definition and load the more complex code from elsewhere. If written as raw javascript, this embedded code would be in string so I think parenscript would work better here. Most likely the ability of parenscript to run as lisp or as javascript could be of some further use but that is another matter.

Now where to get this going would probably start with a composite widget holding the noscript stuff as the first sub-widget with the noscript widget being instructed to load the rest of the widget should javascript be enabled. From there the widget could  be instructed to hold only the entry point as a sub-widget and the required data to retrieve the rest through additional requests. Note here that the widget is the housing on the site for the code while not having the actual code within the widget itself.

Main thing to consider here is the need for authorization so the request should happen through the app's rest api to prevent unauthorized use. Currently the authorization module in my development uses the session to figure out if any given action is authorized. It is built using a positive security model so that even public pages need to be explicitly defined public.

With this model we could define this kind of feature set:
- Javascript could be either raw javascript or anything that compiles into javascript.
- The widget would only hold the generic stuff and an entry point making it lighter when javascript isn't enabled.
- The access to the actual code would be monitored for possible attacks as each access would require an active session or setting the resource as public and therefore embeddable by all.

Then by developing a handler that would process any javascript/parenscript defined within the widget to an external file/entity with the proper rest api access methods, the implementation would allow writing the definitions in two ways that would both be handled the same when in stead of the entry point definition there could be an entire simple script.

This would be a lot to work on and probably an overkill for the task, but it would enable a very neat syntax like `(define-script-widget name permissions entry-code)` where the entry-code could just as well hold an entry point or an entire script. To use this defined resource, we would do exactly the same as with any other widget not complicating anything further for the website developer.

I would like to hear some thought on this as I probably missed a bunch of stuff.

**Comment by ritschmaster** [comment]
As I want to implement some login procedure/system (similar to Weblocks' login) the "private" widgets are on my agenda too. So therefore your description describes a private-widget class which only has to check for a simple boolean value in the session. That boolean value again is set by the login-widget which uses a user defined function to match the passwords - otherwise the developer has to use a specific database. Then delivering HTML- or JavaScript-Code only differs with the used widget.

How exactly do you want to set a resource public/private? For what I have understood of your statements a login (= session-based decision) differs from a public/private resource. Does the user need some kind of token to access the private resource? Please explain that to me.

Using White-listing for every path/widget is not really something I want to have as this seems more specific to the application's needs. A Blacklist would be more appropriate - but you can convince me.

Then next the script-widget itself:
I don't quite understand why the script-widget should be a composite-widget as this causes only (in my opinion) unnecessary HTML-Code. I would rather use a single widget which only generates noscript and script tags as it is sufficient. But maybe I haven't understood it right.

Finally I have to admit that the make-button/make-link functions are pretty ugly and will be refactored out in the next commit. They were necessary as I didn't know how to pass the MAKE-INSTANCE parameters to MAKE-WIDGET. As MAKE-WIDGET is now a macro - which works pretty well - this bypass is not needed anymore and is not really consistent to the rest of the API. Therefore defining a DEFINE-SCRIPT-WIDGET macro/function is something I want to avoid - but you couldn't have known that. So I would rather have something like `(make-widget scope '<script-widget> permissions js-code)`. I left out "name" as it doesn't make sense (to me) to name a widget - but maybe I have left out something? Otherwise you probably meant the id-tag of the HTML block which you can modify/access by using the id-slot:  `(make-widget scope '<widget> :id "important")`.

**Comment by ghost** [comment]
The authorization system I have under my development will be tied to the authentication elements provided to any caveman application, so the developer will be able to choose what ever is the appropriate authentication method for any application from any of the implemented ones or implement a new one. Currently I have implemented POST authentication using postgres with bcrypt for testing and should sometime start getting the http-auth-basic provided by clack to work with it along with OAuth and later client certificates and other keys.

The authorization is called with a simple macro `(with-authorization (permission) &body)` and the permissions for any application are defined as another macro `(defpermission permission-name permission-store)`. This allows the permission to be anything the developer want's as the authorization checks only if the required permission exists within the permission store under permissions. This, however, excludes some special permissions such as public which does not require a permission store as there is nothing to check other than the required permission is "public". Other special permissions may be developed as well such as "user-private" only allowing access if the user accessing is the set owning user as in the case of a user home page. here we would see the permission "user-private" and we would be given the user part of the route to check. To pass to say "www.my-app.com/users/john/refresh-subscribed-products" we would have to check that a user is:
1. logged in
2. is the user "john"

This also allows the permissions be generated by not only authentication, but by other events as well. One example of such even would be the addition of an item to shopping basket generating the permission "customer" that allows the access to checkout. You don't want the people toying around with anything closely related with money. In the checkout example the unauthorized user could be redirected to the shopping basket page and told that there is nothing here.

Why I utilize such model is about how I look at security threats and implement guidelines set by OWASP:
- [Access control](https://www.owasp.org/index.php/Access_Control_Cheat_Sheet#tab=Introduction)
- [REST Authorization](https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Authorization)
- [Positive Security Model](https://www.owasp.org/index.php/Positive_security_model)

The goal is to protect as much as we can so that there is as little attack surface as possible. Also when defining security stuff I prefer to have my tester to say he/she can't get to some url or use some action that is denied by default and then grant that privilege to that permission group rather than finding out that something was allowed by default that shouldn't be. I sure sleep my nights sounder then.

You would be able to use this authorization system with the widgets as soon as I get something public.

Now to the widgets. I was thinking the `make-script-widget` as a shorthand for `make-widget` with script definition. It would expand to just that as to not clutter anything but still be neat. The name I intended to be used as the REST resource url so that an embedable widget with a name of master-script would be accessible from "www.my-app.com/embed/master-script" or something like that. This would allow to have different versions of script be delivered to different permissions as each request would generate a route that could have the permissions checked. Also we could have a special permission "script" defined to be allowed to load the other parts of the scripted program once it is sure that this is no malicious user. The script would run in its own session that is bound to the requesting user's session. This results in ability to prevent weird looking script requests as long as some form of session hardening is used such as binding to IP and other factors. This probably has to be done as middlewares.

The other way would be to have the scripts be stored in /static/js and accessed from there as well. However, this could mess with the delivery of other static assets unless we want to implement the same restrictions to them as well. I'm sure someone would agree to that but I would like to give a choice to have a set extracted from there and accessed from a different route even when they are stored in the same place just to give the embeder a view that these assets are indeed handled differently.

The composite widget proposed was of the fact that there were some special widgets already defined and I thought of reusing them. They could be compiled to simpler code for the end user so that not all html would be there. What I had in mind is that the noscript stuff will be same for all so we can throw that in anyway and compile the actual script into it like this:

In (composite (noscript code/loader))
Out script-widget aka mangled composite-widget

It is not the best solution as it does give some unnecessary overhead and probably would be harder to maintain, but could have worked with the current structure. The other way is to do as you described and define a script-widget class that is probably going to be lighter and easier in the long run. I'm not exactly sure how it would be built internally to generate all the required routes and permission checks for the sub-scripts or should they have to be defined separately and if so how would they be called. This is something we need to discuss.

Hope this clears out some of the confusion you had and raised some more questions.

**Comment by ritschmaster** [comment]
Ok, I think I have understood what you are proposing. The ideas sound good to me. Even the whitelisting approach now. Which brings me to my first question: are you migrating the authentication procedure to some sort of widget? Further it would be great if the widget can check if HTTPS is used because then the password could be sent as plain text and JavaScript would be not required for a login.

At first glance your authorization macro looks easy to use within a widget - e.g. within the render method. Or is that not possible without much work?

> You would be able to use this authorization system with the widgets as soon as I get something public.

Do you have a release date scheduled yet?

> make-script-widget as a shorthand for make-widget with script definition.

So you mean passing Parenscript code to it? Then the name `with-parenscript-to-script-widget` or something like that would be more appropriate. 

Although I get the basic idea of your `make-script-widget`, I don't quite understand the part with the "script running in its own session". That's what I've understood:
1. The user authenticates himself through a login
2. The user loads a page where a `script-widget` is embedded. This widget in turn has created a global path which checks for the authorization. 
3. The client loads the JavaScript-Code from this URL. It is possible for him because the permission "script" authorizes him to do so.
4. The user can interact with the JavaScript program.

I don't think that adding permissions to access /static/js files is a good option. This would limit the developer much more and catches him in the permission box. By pasting files in there the developer should be able to bypass the entire permission system easily. But this brings me to (a nice to have) idea: adding a path on the file system where the developer can place JavaScript files which are delivered automatically under a default permission (which can be changed through a global variable).

The script-widget itself would be - as you mentioned - easier to maintain as a separate class. As the composite widget's code is pretty slim the disadvantages (higher search path for methods, HTML overhead) are bigger than the advantages (using already implemented code). The internal structure probably won't be more difficult than the structure of the navigation widget - which has to create routes too.

**Comment by ghost** [comment]
The authentication module I have would work really simply in a widget as what it currently does is to take the user input and pass that to postgers as is and just read the answer. Did we authenticate or not and if we did, who we authenticated? The answer postgers gines is either nil or the name of the authenticated user. Then all I have to do is write that to the session.

The authorization is used with a single line that I'm intending to get into the `defroute` macro. Currently the `defroute` accepts only a `lambda` or a `defun` as the body, so I would have to redefine that by adding some wrapper for the authorization code into a `defun` with a different name. Then I would have to add that name to the list of allowed symbols of `defroute`. Currently it looks like this

route init stuff
(defun somepage
(with-authorization (permission)
actual page stuff))

I would like to get something like this

route init stuff
(defsecure somepage (permission)
actual page stuff)

or this

secure-route init stuff (permission)
(defun somepage
actual page stuff)

Of course it would be easy to have that one line anywhere as long as someone wants to have it there.

I have that SSL-checking on the TODO list

The release of the code is scheduled to be soon™, meaning our lawyer is pondering with the possible licenses. We are basing the license on AGPL and are now looking into what needs to be changed if anything to suit our company needs. Most likely the changes needed are minor so that we can still use all GPL code. Why we are going for the AGPL is something you might be wondering so let me explain that here next.

All of the applications we are intending to build will use a web based UI and therefore in the case of our client doing some modifications and reselling what they then have as a service. Using the web UI means to us that we need a way to enforce the sharing of development efforts. For this reason we can't really go with the LLGPL. Also we think that as the main use of web software is to have a web interface the AGPL really is the correct choice whether or not business is intended to be made.

About the `with-parenscript-to-script-widget`. This is what I'm after. I want to have a handy shorthand for the power of the underlying system without any clutter in the command. This can be seen from the `with-authorization` macro as well. It is easy to understand and use and if needed, some of the things it does can be augmented without affecting to the line used in any way.

You told that you don't understand the separate session for the script and I admit I didn't really open that idea up so here goes. I intended that as a later developed feature where not all scripts should have all the permissions of the user. This is again about shrinking the attack surface. A script will make different looking requests at a different rate than a human and if we put rate limits and other intrusion detection/prevention mechanisms, we might want to know if a request is made by a known script of certain characteristics or someone claiming to be human or such script and act accordingly.

Also in the case of inactivity timeout in the session, we don't want the requests a script makes to refresh that timeout. There are some other things that just boil down to the script and the actual user being different entities and therefore should in some cases be treated differently. The separate session part is about the ease of having a session as the separator as all that is required on the client side is a cookie that can be set separately for the user and for each script requiring a separate session. ALso a new session is simple to make on the server side too and linking a script to a user session is nothing more than just an entry in the user's session's hashtable. It is not something that needs to be developed right away but will in the end provide another layer of insulation.

About the access of the js. The /static probably is the lesser of the two options I proposed. Having the scripts being able to bypass the whole system is a bad thing and should at least not be encouraged. Also the ability to have scripts just be dropped into a directory and mapped to routes could pose some risks. Hopefully they can be mitigated as that sounds like a great idea. The default permission would probably have to be not externally callable and certainly not embedable. Probably it is a great way to deliver all the sub scripts by having the  directory structure define what can call it. It would work if the main script would always have to be defined and that script would be able to call scripts within a directory that has its name within the js root.

Example: We define a script `my-master-script` using the `script-widget` The script is loaded into the browser and sees that javascript is enabled. This then causes the script to call for a sub script `my-slave-script` at "www.my-app.com/scripts/my-master-script/my-slave-script" The request would have the script identifier that is checked against some automatically built index to find that the script in deed is the `my-master-script` that we know of and that it is requesting a valid sub script. The sub script would then be dispatched as a response.

This just raises the problem of forging  identifiers. So we would need some way to have the scripts being able to not call for any maliciously uploaded ( somehow missed ) sub scripts and call for them to be executed on the server. Or we could have the script directory be secured in another way entirely.

**Comment by ghost** [comment]
Hey I just thought of a better way to handle the script authorization. This one won't need any identifiers so that will be a plus. My idea is to handle the scrip permission tag the same way the user permission tag is handled. So we would have the script tag to identify that the session user is allowed to call the top level scripts such as "www.my-app.com/scripts/master" unless the scripts have some special permissions defined. Then after calling and gaining access to the master-script, the path of the accessed script is added to the user's session under scripts. This allows the master script to make requests to /scripts/master-script/slave-script and its neighbors unless some special permissions have been defined.

In my authorization system, all I would need to do to differentiate script from users would be to change the tag requested. This would then make the script authorization work in line with other authorizations and be simple to use. Also the default permission script could be defined as public, granted through an event or be tied to some other permission such as user. The default would still be private so it would be in line with the rest there too.

Currently the the public permission must be defined to be able to use it and the same can be done with the script permission. All that is needed to make it easy to use is to have it defined but commented out in the application skeleton with a description like "To allow javascript loading uncomment this line".

To me that sounds great but what do you think?

The only worry then is to make the scripts directory read-only and and have the application fail to start if it is not.

**Comment by ritschmaster** [comment]
Ok, the authentication module looks cool to me but the authorization sounds not so great (currently). Because integrating it into `defroute` would have some major drawbacks. For example, if it is not coupled with `defroute` something like that would be possbile:
`(defmethod render-widget (this <some-widget>)
     (with-authentication (context)
          (with-authorization (permission) 
`

**Comment by ritschmaster** [comment]
Ok, the authentication module looks cool to me but the authorization sounds not so great (currently). Because integrating it into `defroute` would have some major drawbacks. For example, if it is not coupled with `defroute` something like that would be possbile:
`(defmethod render-widget (this <some-widget>)
    (with-authentication (context) 
      (with-authorization (permission) 
        "<p>This is some secured text</p>")))`
So this would be really cool. Not only for using it within widgets, but it would be possible to use `with-authorization` in a lambda too.

The usage of AGPL won't be a problem to me, as long as you don't want to integrate the code in this project (at the moment). I still have to do research on the pros and cons of the AGPL. Currently the AGPL looks pretty bad to me, because even the license effectively prohibits you from charging money for anything as soon as a server is running.

Your explanation for the separate script really helps and makes sense to me.

Placing scripts under /static would ease the use of server delivered js-libraries. For example if you need a specific version of jQuery which is not available as CDN that this would not require some special permission to access it. That was my main thought on that bypass. But you can enlighten me on that too.

> This just raises the problem of forging identifiers.

This problem could be solved with either a private/public key pair or a symmetric key. The `script-widget` delivers either dynamic in the script or hidden in the HTML a signed/an encrypted value. Then the client has to send this signed/encrypted value back. If the server can verfiy/decrypt it, the request is authorized. But your second way looks fine to me too, probably stabler as I might missed something.

Why does the scripts directory has to be read-only? Do you mean on file system level because then I won't understand why.

**Comment by ghost** [comment]
I intended to have the authorization integrated into the `defroute` but not force the use of the version of it where the integration has happened. Both versions would still be available. This means that the integration to widgets is still possible but just not mandatory. This gives additional options to the users of the system not forcing them to use any specific way of using the system. What I would then like to check as the top most middleware is that at some point the request has been authorized. It won't matter where as long as the authorization has happened. This could possibly be checked with a variable in the `env` that is nulled for every request and then needs to be set for every response or the system raises an error.

The forging of identifiers is a problem with any keys contained within the scripts as an attacker would be able to extract the keys and the use them to forge requests. The only way that I know to alleviate that problem is to have the whole script be processed while it is encrypted and/or  heavily obfuscated. This however would raise another problem for us as we intended to release the js under AGPL as well so no obfuscation and encryption would be possible to crack as almost all of the encrypted content would already be known to the attacker.

The read-only script directory is another security measure for the production environment. It would not be used in a development environment and in a testing environment a read-write script directory should raise a warning. When used on a production environment, a read-write script directory should raise an error. This is because our though of "if something can go wrong, no matter how small the chance is, it will eventually go wrong".

This is why we don't want to have a public facing web service having any write permissions that it doesn't need. All of the ill effects of this can be alleviated by splitting the application to the public part and the management part running on different instances of LISP. This is done by having the file system configured to give read-only access to the public facing part and read-write access to the management part.

AGPL doesn't seem to give us any additional burden on any of our analyses. What is the problem you are having? Our business model is built around providing services to this code we write and the products built with this code. Therefore, the code itself won't provide any hurdles for us to have open sourced under AGPL. I won't go into specifics about our business model as that is a company secret, but the code itself is not the product we sell. If it were, we would keep it closed as LLGPL [doesn't require anything really to be published openly](http://www.ifosslr.org/ifosslr/article/view/75).

We have done probably way too much analysis on this but what can you do when your major isn't in computer science but in business administration.

**Comment by ritschmaster** [comment]
Generally I don't have any problem with the AGPL especially with an end-user application (like a web application). But using AGPL for a (small) library might keep away potential users which does not really help the library to succeed.

Now to get some conclusion of the discussion: do you have any specific wishes towards this library to be implemented? My agenda for the next week(s) will be:
- Refactor the button/link widgets
- Implement a login procedure (as I need it myself I have to do it right now but it certainly won't be as sophisticated as in your software)
- Add Bootstrap
- Create an example application

**Comment by ghost** [comment]
The main idea of my posting was to get some light on the javascript roadmap and this discussion has definitely provided you and me both with some ideas on how it could work. At some point I might go and implement that myself unless you beat me to it. We'll see who finds the time and need faster.

About the login procedure, you might want to take a look at [this](https://github.com/fukamachi/lack/blob/master/src/middleware/auth/basic.lisp) as it is already a part of caveman through clack and looks simple enough.

I look forward to seeing the example application for reference. It will probably help more than just me a bunch. Have a fun time coding.

**Comment by ritschmaster** [comment]
Yeah, I think that too. Think you very much for the Link! If you have still thoughts or ideas you can share them anytime!
